/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BillableItemsTable: typeof import('./../../resources/js/components/BillableItemsTable.vue')['default']
    ChatHistoryPanel: typeof import('./../../resources/js/components/chat/ChatHistoryPanel.vue')['default']
    ClientFormFields: typeof import('./../../resources/js/components/clients/ClientFormFields.vue')['default']
    ColorField: typeof import('./../../resources/js/components/inputs/ColorField.vue')['default']
    CurrencyField: typeof import('./../../resources/js/components/inputs/CurrencyField.vue')['default']
    DateField: typeof import('./../../resources/js/components/inputs/DateField.vue')['default']
    DetailsPage: typeof import('./../../resources/js/components/DetailsPage.vue')['default']
    EditableRowsTable: typeof import('./../../resources/js/components/EditableRowsTable.vue')['default']
    GlobalDialog: typeof import('./../../resources/js/components/GlobalDialog.vue')['default']
    GlobalToast: typeof import('./../../resources/js/components/GlobalToast.vue')['default']
    ImageUploadField: typeof import('./../../resources/js/components/inputs/ImageUploadField.vue')['default']
    MaskedTextField: typeof import('./../../resources/js/components/inputs/MaskedTextField.vue')['default']
    ModalityCard: typeof import('./../../resources/js/components/ModalityCard.vue')['default']
    PasswordField: typeof import('./../../resources/js/components/inputs/PasswordField.vue')['default']
    ReadOnlyDetailsPage: typeof import('./../../resources/js/components/ReadOnlyDetailsPage.vue')['default']
    ServerAutocomplete: typeof import('./../../resources/js/components/inputs/ServerAutocomplete.vue')['default']
    StatusChip: typeof import('./../../resources/js/components/StatusChip.vue')['default']
    TablePage: typeof import('./../../resources/js/components/TablePage.vue')['default']
    TimeField: typeof import('./../../resources/js/components/inputs/TimeField.vue')['default']
  }
}
